import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

serve(async (req) => {
  try {
    // Get the authorization header
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Missing authorization header' }), {
        status: 401,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Create Supabase client with service role for admin operations
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
    )

    // Create user client to verify the token
    const supabaseUser = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    )

    // Get the authenticated user
    const { data: { user }, error: userError } = await supabaseUser.auth.getUser()
    if (userError || !user) {
      return new Response(JSON.stringify({ error: 'Invalid or expired token' }), {
        status: 401,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Verify user has supervisor or admin role
    const { data: profile, error: profileError } = await supabaseAdmin
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (profileError || !profile) {
      return new Response(JSON.stringify({ error: 'User profile not found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    if (profile.role !== 'supervisor' && profile.role !== 'admin') {
      return new Response(JSON.stringify({ error: 'Only supervisors and admins can generate consolidated reports' }), {
        status: 403,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Parse the request body
    const { windFarmId } = await req.json()
    if (!windFarmId) {
      return new Response(JSON.stringify({ error: 'windFarmId is required' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Get wind farm details
    const { data: windFarm, error: farmError } = await supabaseAdmin
      .from('wind_farm')
      .select('*')
      .eq('id', windFarmId)
      .single()

    if (farmError || !windFarm) {
      return new Response(JSON.stringify({ error: 'Wind farm not found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Get all turbines with blades and their inspections/defects
    const { data: turbines, error: turbinesError } = await supabaseAdmin
      .from('turbine')
      .select(`
        id, name,
        blades:blade(
          id, position, serial_number,
          inspections:inspection(
            id, status, stage, scheduled_date, completed_at,
            defects:defect(id, type, severity, description, distance_from_root)
          )
        )
      `)
      .eq('wind_farm_id', windFarmId)
      .order('name')

    if (turbinesError) {
      return new Response(JSON.stringify({ error: 'Failed to fetch turbine data' }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Build consolidated report content
    const reportLines: string[] = [
      '═══════════════════════════════════════════════════════════════',
      '            CONSOLIDATED WIND FARM INSPECTION REPORT',
      '═══════════════════════════════════════════════════════════════',
      '',
      `Report Generated: ${new Date().toISOString()}`,
      `Generated By:     ${user.email}`,
      '',
      '───────────────────────────────────────────────────────────────',
      'WIND FARM INFORMATION',
      '───────────────────────────────────────────────────────────────',
      `Name:     ${windFarm.name}`,
      `Location: ${windFarm.location || 'N/A'}`,
      `Total Turbines: ${turbines?.length || 0}`,
      '',
    ]

    // Summary by severity across the whole farm
    const severityCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 }
    let totalDefects = 0
    let totalInspections = 0

    for (const turbine of (turbines || [])) {
      for (const blade of (turbine.blades || [])) {
        for (const inspection of (blade.inspections || [])) {
          totalInspections++
          for (const defect of (inspection.defects || [])) {
            totalDefects++
            const sev = defect.severity as number
            if (sev >= 1 && sev <= 5) {
              severityCounts[sev]++
            }
          }
        }
      }
    }

    reportLines.push('───────────────────────────────────────────────────────────────')
    reportLines.push('FARM-WIDE SUMMARY')
    reportLines.push('───────────────────────────────────────────────────────────────')
    reportLines.push(`Total Inspections: ${totalInspections}`)
    reportLines.push(`Total Defects:     ${totalDefects}`)
    reportLines.push('')
    reportLines.push('Defects by Severity:')
    reportLines.push(`  Severity 1 (Minor):    ${severityCounts[1]}`)
    reportLines.push(`  Severity 2 (Low):      ${severityCounts[2]}`)
    reportLines.push(`  Severity 3 (Moderate): ${severityCounts[3]}`)
    reportLines.push(`  Severity 4 (High):     ${severityCounts[4]}`)
    reportLines.push(`  Severity 5 (Critical): ${severityCounts[5]}`)
    reportLines.push('')

    // Detail per turbine
    reportLines.push('───────────────────────────────────────────────────────────────')
    reportLines.push('DEFECTS BY TURBINE')
    reportLines.push('───────────────────────────────────────────────────────────────')
    reportLines.push('')

    for (const turbine of (turbines || [])) {
      let turbineDefectCount = 0
      const turbineSeverity: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 }

      for (const blade of (turbine.blades || [])) {
        for (const inspection of (blade.inspections || [])) {
          for (const defect of (inspection.defects || [])) {
            turbineDefectCount++
            const sev = defect.severity as number
            if (sev >= 1 && sev <= 5) {
              turbineSeverity[sev]++
            }
          }
        }
      }

      reportLines.push(`  Turbine: ${turbine.name}`)
      reportLines.push(`  Total Defects: ${turbineDefectCount}`)
      if (turbineDefectCount > 0) {
        reportLines.push(`  Severity Distribution: S1=${turbineSeverity[1]} S2=${turbineSeverity[2]} S3=${turbineSeverity[3]} S4=${turbineSeverity[4]} S5=${turbineSeverity[5]}`)
      }
      reportLines.push('')
    }

    reportLines.push('═══════════════════════════════════════════════════════════════')
    reportLines.push('                       END OF REPORT')
    reportLines.push('═══════════════════════════════════════════════════════════════')

    const reportContent = reportLines.join('\n')

    // Store report file in reports bucket
    const fileName = `consolidated_${windFarmId}_${Date.now()}.txt`
    const storagePath = `consolidated/${fileName}`

    const { error: uploadError } = await supabaseAdmin
      .storage
      .from('reports')
      .upload(storagePath, new TextEncoder().encode(reportContent), {
        contentType: 'text/plain',
        upsert: false,
      })

    if (uploadError) {
      return new Response(JSON.stringify({ error: 'Failed to store report file' }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Create report database record
    const reportFilename = `Consolidated Report - ${windFarm.name}`

    const { data: report, error: reportError } = await supabaseAdmin
      .from('report')
      .insert({
        type: 'consolidated',
        reference_id: windFarmId,
        generated_by: user.id,
        storage_path: storagePath,
        filename: reportFilename,
        generated_at: new Date().toISOString(),
      })
      .select()
      .single()

    if (reportError) {
      // Attempt to clean up the uploaded file
      await supabaseAdmin.storage.from('reports').remove([storagePath])
      return new Response(JSON.stringify({ error: 'Failed to create report record' }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    return new Response(JSON.stringify({ report }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    })
  } catch (err) {
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }
})
